'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SRGoogleSearch
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="urn:GoogleSearch", ConfigurationName:="SRGoogleSearch.GoogleSearchPort")>  _
    Public Interface GoogleSearchPort
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:GoogleSearchAction", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function doGetCachedPage(ByVal key As String, ByVal url As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return"), System.Xml.Serialization.SoapElementAttribute(DataType:="base64Binary")> Byte()
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:GoogleSearchAction", ReplyAction:="*")>  _
        Function doGetCachedPageAsync(ByVal key As String, ByVal url As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return"), System.Xml.Serialization.SoapElementAttribute(DataType:="base64Binary")> System.Threading.Tasks.Task(Of Byte())
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:GoogleSearchAction", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded)>  _
        Function doSpellingSuggestion(ByVal key As String, ByVal phrase As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> String
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:GoogleSearchAction", ReplyAction:="*")>  _
        Function doSpellingSuggestionAsync(ByVal key As String, ByVal phrase As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:GoogleSearchAction", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(Style:=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults:=true, Use:=System.ServiceModel.OperationFormatUse.Encoded),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(ResultElement))>  _
        Function doGoogleSearch(ByVal key As String, ByVal q As String, ByVal start As Integer, ByVal maxResults As Integer, ByVal filter As Boolean, ByVal restrict As String, ByVal safeSearch As Boolean, ByVal lr As String, ByVal ie As String, ByVal oe As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> SRGoogleSearch.GoogleSearchResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="urn:GoogleSearchAction", ReplyAction:="*")>  _
        Function doGoogleSearchAsync(ByVal key As String, ByVal q As String, ByVal start As Integer, ByVal maxResults As Integer, ByVal filter As Boolean, ByVal restrict As String, ByVal safeSearch As Boolean, ByVal lr As String, ByVal ie As String, ByVal oe As String) As <System.ServiceModel.MessageParameterAttribute(Name:="return")> System.Threading.Tasks.Task(Of SRGoogleSearch.GoogleSearchResult)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:GoogleSearch")>  _
    Partial Public Class GoogleSearchResult
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private documentFilteringField As Boolean
        
        Private searchCommentsField As String
        
        Private estimatedTotalResultsCountField As Integer
        
        Private estimateIsExactField As Boolean
        
        Private resultElementsField() As ResultElement
        
        Private searchQueryField As String
        
        Private startIndexField As Integer
        
        Private endIndexField As Integer
        
        Private searchTipsField As String
        
        Private directoryCategoriesField() As DirectoryCategory
        
        Private searchTimeField As Double
        
        '''<remarks/>
        Public Property documentFiltering() As Boolean
            Get
                Return Me.documentFilteringField
            End Get
            Set
                Me.documentFilteringField = value
                Me.RaisePropertyChanged("documentFiltering")
            End Set
        End Property
        
        '''<remarks/>
        Public Property searchComments() As String
            Get
                Return Me.searchCommentsField
            End Get
            Set
                Me.searchCommentsField = value
                Me.RaisePropertyChanged("searchComments")
            End Set
        End Property
        
        '''<remarks/>
        Public Property estimatedTotalResultsCount() As Integer
            Get
                Return Me.estimatedTotalResultsCountField
            End Get
            Set
                Me.estimatedTotalResultsCountField = value
                Me.RaisePropertyChanged("estimatedTotalResultsCount")
            End Set
        End Property
        
        '''<remarks/>
        Public Property estimateIsExact() As Boolean
            Get
                Return Me.estimateIsExactField
            End Get
            Set
                Me.estimateIsExactField = value
                Me.RaisePropertyChanged("estimateIsExact")
            End Set
        End Property
        
        '''<remarks/>
        Public Property resultElements() As ResultElement()
            Get
                Return Me.resultElementsField
            End Get
            Set
                Me.resultElementsField = value
                Me.RaisePropertyChanged("resultElements")
            End Set
        End Property
        
        '''<remarks/>
        Public Property searchQuery() As String
            Get
                Return Me.searchQueryField
            End Get
            Set
                Me.searchQueryField = value
                Me.RaisePropertyChanged("searchQuery")
            End Set
        End Property
        
        '''<remarks/>
        Public Property startIndex() As Integer
            Get
                Return Me.startIndexField
            End Get
            Set
                Me.startIndexField = value
                Me.RaisePropertyChanged("startIndex")
            End Set
        End Property
        
        '''<remarks/>
        Public Property endIndex() As Integer
            Get
                Return Me.endIndexField
            End Get
            Set
                Me.endIndexField = value
                Me.RaisePropertyChanged("endIndex")
            End Set
        End Property
        
        '''<remarks/>
        Public Property searchTips() As String
            Get
                Return Me.searchTipsField
            End Get
            Set
                Me.searchTipsField = value
                Me.RaisePropertyChanged("searchTips")
            End Set
        End Property
        
        '''<remarks/>
        Public Property directoryCategories() As DirectoryCategory()
            Get
                Return Me.directoryCategoriesField
            End Get
            Set
                Me.directoryCategoriesField = value
                Me.RaisePropertyChanged("directoryCategories")
            End Set
        End Property
        
        '''<remarks/>
        Public Property searchTime() As Double
            Get
                Return Me.searchTimeField
            End Get
            Set
                Me.searchTimeField = value
                Me.RaisePropertyChanged("searchTime")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:GoogleSearch")>  _
    Partial Public Class ResultElement
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private summaryField As String
        
        Private uRLField As String
        
        Private snippetField As String
        
        Private titleField As String
        
        Private cachedSizeField As String
        
        Private relatedInformationPresentField As Boolean
        
        Private hostNameField As String
        
        Private directoryCategoryField As DirectoryCategory
        
        Private directoryTitleField As String
        
        '''<remarks/>
        Public Property summary() As String
            Get
                Return Me.summaryField
            End Get
            Set
                Me.summaryField = value
                Me.RaisePropertyChanged("summary")
            End Set
        End Property
        
        '''<remarks/>
        Public Property URL() As String
            Get
                Return Me.uRLField
            End Get
            Set
                Me.uRLField = value
                Me.RaisePropertyChanged("URL")
            End Set
        End Property
        
        '''<remarks/>
        Public Property snippet() As String
            Get
                Return Me.snippetField
            End Get
            Set
                Me.snippetField = value
                Me.RaisePropertyChanged("snippet")
            End Set
        End Property
        
        '''<remarks/>
        Public Property title() As String
            Get
                Return Me.titleField
            End Get
            Set
                Me.titleField = value
                Me.RaisePropertyChanged("title")
            End Set
        End Property
        
        '''<remarks/>
        Public Property cachedSize() As String
            Get
                Return Me.cachedSizeField
            End Get
            Set
                Me.cachedSizeField = value
                Me.RaisePropertyChanged("cachedSize")
            End Set
        End Property
        
        '''<remarks/>
        Public Property relatedInformationPresent() As Boolean
            Get
                Return Me.relatedInformationPresentField
            End Get
            Set
                Me.relatedInformationPresentField = value
                Me.RaisePropertyChanged("relatedInformationPresent")
            End Set
        End Property
        
        '''<remarks/>
        Public Property hostName() As String
            Get
                Return Me.hostNameField
            End Get
            Set
                Me.hostNameField = value
                Me.RaisePropertyChanged("hostName")
            End Set
        End Property
        
        '''<remarks/>
        Public Property directoryCategory() As DirectoryCategory
            Get
                Return Me.directoryCategoryField
            End Get
            Set
                Me.directoryCategoryField = value
                Me.RaisePropertyChanged("directoryCategory")
            End Set
        End Property
        
        '''<remarks/>
        Public Property directoryTitle() As String
            Get
                Return Me.directoryTitleField
            End Get
            Set
                Me.directoryTitleField = value
                Me.RaisePropertyChanged("directoryTitle")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:GoogleSearch")>  _
    Partial Public Class DirectoryCategory
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private fullViewableNameField As String
        
        Private specialEncodingField As String
        
        '''<remarks/>
        Public Property fullViewableName() As String
            Get
                Return Me.fullViewableNameField
            End Get
            Set
                Me.fullViewableNameField = value
                Me.RaisePropertyChanged("fullViewableName")
            End Set
        End Property
        
        '''<remarks/>
        Public Property specialEncoding() As String
            Get
                Return Me.specialEncodingField
            End Get
            Set
                Me.specialEncodingField = value
                Me.RaisePropertyChanged("specialEncoding")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface GoogleSearchPortChannel
        Inherits SRGoogleSearch.GoogleSearchPort, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GoogleSearchPortClient
        Inherits System.ServiceModel.ClientBase(Of SRGoogleSearch.GoogleSearchPort)
        Implements SRGoogleSearch.GoogleSearchPort
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function doGetCachedPage(ByVal key As String, ByVal url As String) As Byte() Implements SRGoogleSearch.GoogleSearchPort.doGetCachedPage
            Return MyBase.Channel.doGetCachedPage(key, url)
        End Function
        
        Public Function doGetCachedPageAsync(ByVal key As String, ByVal url As String) As System.Threading.Tasks.Task(Of Byte()) Implements SRGoogleSearch.GoogleSearchPort.doGetCachedPageAsync
            Return MyBase.Channel.doGetCachedPageAsync(key, url)
        End Function
        
        Public Function doSpellingSuggestion(ByVal key As String, ByVal phrase As String) As String Implements SRGoogleSearch.GoogleSearchPort.doSpellingSuggestion
            Return MyBase.Channel.doSpellingSuggestion(key, phrase)
        End Function
        
        Public Function doSpellingSuggestionAsync(ByVal key As String, ByVal phrase As String) As System.Threading.Tasks.Task(Of String) Implements SRGoogleSearch.GoogleSearchPort.doSpellingSuggestionAsync
            Return MyBase.Channel.doSpellingSuggestionAsync(key, phrase)
        End Function
        
        Public Function doGoogleSearch(ByVal key As String, ByVal q As String, ByVal start As Integer, ByVal maxResults As Integer, ByVal filter As Boolean, ByVal restrict As String, ByVal safeSearch As Boolean, ByVal lr As String, ByVal ie As String, ByVal oe As String) As SRGoogleSearch.GoogleSearchResult Implements SRGoogleSearch.GoogleSearchPort.doGoogleSearch
            Return MyBase.Channel.doGoogleSearch(key, q, start, maxResults, filter, restrict, safeSearch, lr, ie, oe)
        End Function
        
        Public Function doGoogleSearchAsync(ByVal key As String, ByVal q As String, ByVal start As Integer, ByVal maxResults As Integer, ByVal filter As Boolean, ByVal restrict As String, ByVal safeSearch As Boolean, ByVal lr As String, ByVal ie As String, ByVal oe As String) As System.Threading.Tasks.Task(Of SRGoogleSearch.GoogleSearchResult) Implements SRGoogleSearch.GoogleSearchPort.doGoogleSearchAsync
            Return MyBase.Channel.doGoogleSearchAsync(key, q, start, maxResults, filter, restrict, safeSearch, lr, ie, oe)
        End Function
    End Class
End Namespace
